[package]
name = "anagram"
version = "0.1.0"
authors = ["Telmo Costa <telmo.ferreira.costa@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
